languageCode: ja
enableGitInfo: true
hasCJKLanguage: true
pluralizeListTitles: false
footnoteReturnLinkContents: ↩
paginatePath: ''

baseURL: 'https://ress.39.gy/'
title: ress.39.gy
copyright: '&copy; 2016 Ress'

theme: stack
DefaultContentLanguage: ja

params:
  mainSections:
    - post

  dateFormat:
    published: 'Jan 02, 2006'
    lastUpdated: 'Jan 02, 2006 15:04 MST'

  sidebar:
    emoji: "\U0001F98B"
    subtitle: noob から hacker になりたい
    avatar:
      local: true
      src: img/avatar.png

  article:
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: utterances
    utterances:
      repo: ress997/blog-comment
      issueTerm: pathname
      theme: preferred-color-scheme

  widgets:
    enabled:
      - search
      - archives
      - tag-cloud
    archives:
      limit: 5
    tagCloud:
      limit: 10

  defaultImage:
    opengraph:
      enabled: false
      local: false
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: false
    content:
      enabled: false

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: about
      weight: 2
    - name: Archives
      url: archives
      weight: 3
    - name: Search
      url: search
      weight: 4

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

markup:
  highlight:
    noClasses: false

taxonomies:
  category: categories
  tag: tags
