version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang
        environment:
          HUGO_VERSION: "0.58.3"
jobs:
  checkout_code:
    executor:
      name: default
    working_directory: ~/hugo
    steps:
      - checkout
      - save_cache:
          key: code-{{ epoch }}
          paths:
            - ~/hugo
  build:
    executor:
      name: default
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: code
      - run: git clone -b master --single-branch --depth=1 https://github.com/ress997/hugo-ran.git themes/ran
      - run:
          name: Download hugo
          command: |
            wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" -O hugo.tar.gz
            tar xzf hugo.tar.gz hugo
            rm -rf hugo.tar.gz
      - run: ./hugo --minify
      - save_cache:
          key: hugo-build-{{ epoch }}
          paths:
            - ~/hugo
  deploy:
    docker:
      - image: circleci/node
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-build
      - restore_cache:
          keys:
            - yarn-dep-firebase
      - run: yarn add firebase-tools
      - save_cache:
          key: yarn-dep-firebase-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - run: yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
