name: Build and Deploy
on:
  push:
    branches:
    - main
  repository_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download theme
        uses: actions/checkout@v2
        with:
          repository: CaiJimmy/hugo-theme-stack
          path: themes/stack

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --gc --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ress.39.gy
