name: Build and Deploy
on:
  push:
  pull_request:
  repository_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  main:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Download theme
        uses: actions/checkout@v2
        with:
          repository: ress997/hugo-robust
          path: themes/robust

      - name: Download hugo
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget "https://github.com/gohugoio/hugo/releases/download/v${VERSION}/hugo_extended_${VERSION}_Linux-64bit.tar.gz" -O hugo.tar.gz
          tar xzf hugo.tar.gz hugo
          rm -rf hugo.tar.gz

      - name: Build
        run: ./hugo --minify

      - name: Optimize AMP
        uses: asurbernardo/amp-optimizer-action@1.0.2
        if: github.event_name == 'repository_dispatch' || (github.ref == 'refs/heads/master' && github.event_name != 'pull_request')
        with:
          root: 'public/amp'

      - name: Cache node_modules
        uses: actions/cache@v1
        if: github.event_name == 'repository_dispatch' || (github.ref == 'refs/heads/master' && github.event_name != 'pull_request')
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-blog-${{ github.sha }}
          restore-keys: ${{ runner.os }}-blog

      - name: Install firebase-tools
        if: github.event_name == 'repository_dispatch' || (github.ref == 'refs/heads/master' && github.event_name != 'pull_request')
        run: yarn add firebase-tools

      - name: Push file to Firebase Hosting
        if: github.event_name == 'repository_dispatch' || (github.ref == 'refs/heads/master' && github.event_name != 'pull_request')
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn run deploy
